### ISSUE TITLE
Source code of baseline and standard FedAvg

### ISSUE THREAD

**Issue by ywang037** [VeritasXu/Ternary-Federated#1]
Hi, wondering if you can also upload the source code for the implementation of the baseline and standard FedAvg that is reported in your paper. I wish to regenerate the results of your paper but didn't find the implementation of baseline and FedAvg. Thanks a lot if you can also upload these two algorithms.

**Comment by VeritasXu** [comment]
Hi, sorry for the late reply. FedAvg is a standard federated learning method. And the implementation of CMFL is given by HyperionZhou at https://github.com/HyperionZhou/CMFL.git.

Hope this will help.

Kind regards.

**Comment by VeritasXu** [comment]
Thanks for your comment. Code provided. If necessary, I will re-open this issue.
